import { create } from 'zustand';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { useHotkeyModeStore } from './hotkeyModeStore';

export type ContentType = 'text' | 'url' | 'code' | 'file' | 'image';

export interface Settings {
  hotkey: string;
  launch_at_startup: boolean;
  history_limit: number;
  theme: 'light' | 'dark' | 'system';
  font_size: number;
  show_timestamps: boolean;
  excluded_apps: string[];
  excluded_types: ContentType[];
  intercept_paste: boolean;
  ignore_transient: boolean;
  ignore_autogenerated: boolean;
  ignore_concealed: boolean;
  sticky_mode: boolean;
}

interface SettingsState {
  settings: Settings;
  isLoading: boolean;
  error: string | null;
  isSettingsOpen: boolean;

  loadSettings: () => Promise<void>;
  updateSettings: (settings: Partial<Settings>) => Promise<void>;
  setHotkey: (hotkey: string) => Promise<void>;
  setTheme: (theme: Settings['theme']) => Promise<void>;
  addExcludedApp: (appId: string) => Promise<void>;
  removeExcludedApp: (appId: string) => Promise<void>;
  toggleExcludedType: (type: ContentType) => Promise<void>;
  openSettings: () => void;
  closeSettings: () => void;
  applyTheme: () => void;
  setupListeners: () => Promise<() => void>;
}

const defaultSettings: Settings = {
  hotkey: 'Command+Shift+V',
  launch_at_startup: false,
  history_limit: 100,
  theme: 'system',
  font_size: 14,
  show_timestamps: true,
  excluded_apps: [],
  excluded_types: [],
  intercept_paste: true,
  ignore_transient: true,
  ignore_autogenerated: true,
  ignore_concealed: true,
  sticky_mode: false,
};

export const useSettingsStore = create<SettingsState>((set, get) => ({
  settings: defaultSettings,
  isLoading: false,
  error: null,
  isSettingsOpen: false,

  loadSettings: async () => {
    set({ isLoading: true, error: null });
    try {
      const settings = await invoke<Settings>('get_settings');
      set({ settings, isLoading: false });
      get().applyTheme();
    } catch (error) {
      set({ error: String(error), isLoading: false });
    }
  },

  updateSettings: async (partial) => {
    const newSettings = { ...get().settings, ...partial };
    try {
      await invoke('update_settings', { settings: newSettings });
      set({ settings: newSettings });
      get().applyTheme();
    } catch (error) {
      set({ error: String(error) });
    }
  },

  setHotkey: async (hotkey) => {
    try {
      const settings = await invoke<Settings>('set_hotkey', { hotkey });
      set({ settings });
      await invoke('register_hotkey', { hotkey });
    } catch (error) {
      set({ error: String(error) });
    }
  },

  setTheme: async (theme) => {
    try {
      const settings = await invoke<Settings>('set_theme', { theme });
      set({ settings });
      get().applyTheme();
    } catch (error) {
      set({ error: String(error) });
    }
  },

  addExcludedApp: async (appId) => {
    try {
      const settings = await invoke<Settings>('add_excluded_app', { appId });
      set({ settings });
    } catch (error) {
      set({ error: String(error) });
    }
  },

  removeExcludedApp: async (appId) => {
    try {
      const settings = await invoke<Settings>('remove_excluded_app', { appId });
      set({ settings });
    } catch (error) {
      set({ error: String(error) });
    }
  },

  toggleExcludedType: async (type) => {
    try {
      const settings = await invoke<Settings>('toggle_excluded_type', { typeId: type });
      set({ settings });
    } catch (error) {
      set({ error: String(error) });
    }
  },

  openSettings: () => {
    set({ isSettingsOpen: true });
    invoke('set_settings_open', { open: true }).catch(() => {});
  },
  closeSettings: async () => {
    set({ isSettingsOpen: false });
    invoke('set_settings_open', { open: false }).catch(() => {});
    if (get().settings.sticky_mode) {
      // Sticky mode on: exit hotkey mode so modifier-release polling
      // stops trying to auto-dismiss.
      useHotkeyModeStore.getState().exitHotkeyMode();
      invoke('exit_hotkey_mode').catch(() => {});
    } else {
      // Sticky mode off: dismiss unless modifiers are still held
      // (user might have re-pressed them to continue cycling).
      const held = await invoke<boolean>('are_modifiers_held').catch(() => false);
      if (!held) {
        invoke('exit_hotkey_mode').catch(() => {});
        useHotkeyModeStore.getState().exitHotkeyMode();
        invoke('hide_window').catch(() => {});
      }
    }
  },

  applyTheme: () => {
    const { theme } = get().settings;
    const root = document.documentElement;
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const isDark = theme === 'dark' || (theme === 'system' && prefersDark);
    root.classList.toggle('dark', isDark);
  },

  setupListeners: async () => {
    const unlisten = await listen('noop', () => {});
    return () => unlisten();
  },
}));
