use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::sync::Mutex;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Settings {
    #[serde(default = "default_hotkey")]
    pub hotkey: String,

    #[serde(default)]
    pub launch_at_startup: bool,

    #[serde(default = "default_history_limit")]
    pub history_limit: u32,

    #[serde(default = "default_theme")]
    pub theme: String,

    #[serde(default = "default_font_size")]
    pub font_size: u32,

    #[serde(default = "default_true")]
    pub show_timestamps: bool,

    /// Bundle-id substrings of apps whose clipboard writes should be ignored
    /// (e.g. dictation tools).
    #[serde(default)]
    pub excluded_apps: Vec<String>,

    /// Content types to ignore: "text", "url", "code", "file", "image".
    #[serde(default)]
    pub excluded_types: Vec<String>,

    #[serde(default = "default_true")]
    pub ignore_transient: bool,

    #[serde(default = "default_true")]
    pub ignore_autogenerated: bool,

    #[serde(default = "default_true")]
    pub ignore_concealed: bool,

    #[serde(default)]
    pub sticky_mode: bool,
}

fn default_hotkey() -> String {
    #[cfg(target_os = "macos")]
    return "Command+Shift+V".to_string();
    #[cfg(not(target_os = "macos"))]
    return "Ctrl+Shift+V".to_string();
}
fn default_history_limit() -> u32 {
    100
}
fn default_theme() -> String {
    "system".to_string()
}
fn default_font_size() -> u32 {
    14
}
fn default_true() -> bool {
    true
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            hotkey: default_hotkey(),
            launch_at_startup: false,
            history_limit: default_history_limit(),
            theme: default_theme(),
            font_size: default_font_size(),
            show_timestamps: true,
            excluded_apps: Vec::new(),
            excluded_types: Vec::new(),
            ignore_transient: true,
            ignore_autogenerated: true,
            ignore_concealed: true,
            sticky_mode: false,
        }
    }
}

pub struct SettingsManager {
    settings: Mutex<Settings>,
    path: PathBuf,
}

impl SettingsManager {
    pub fn new(app_data_dir: PathBuf) -> Self {
        std::fs::create_dir_all(&app_data_dir).ok();
        let path = app_data_dir.join("settings.json");
        let settings = if path.exists() {
            std::fs::read_to_string(&path)
                .ok()
                .and_then(|s| serde_json::from_str(&s).ok())
                .unwrap_or_default()
        } else {
            Settings::default()
        };
        Self {
            settings: Mutex::new(settings),
            path,
        }
    }

    pub fn get(&self) -> Settings {
        self.settings.lock().unwrap().clone()
    }

    pub fn update(&self, new_settings: Settings) -> Result<(), String> {
        let mut s = self.settings.lock().unwrap();
        *s = new_settings;
        let json = serde_json::to_string_pretty(&*s).map_err(|e| e.to_string())?;
        std::fs::write(&self.path, json).map_err(|e| e.to_string())?;
        Ok(())
    }

    pub fn update_field<F>(&self, updater: F) -> Result<Settings, String>
    where
        F: FnOnce(&mut Settings),
    {
        let mut s = self.settings.lock().unwrap();
        updater(&mut s);
        let json = serde_json::to_string_pretty(&*s).map_err(|e| e.to_string())?;
        std::fs::write(&self.path, json).map_err(|e| e.to_string())?;
        Ok(s.clone())
    }
}

#[tauri::command]
pub async fn get_settings(manager: tauri::State<'_, SettingsManager>) -> Result<Settings, String> {
    Ok(manager.get())
}

#[tauri::command]
pub async fn update_settings<R: tauri::Runtime>(
    _app: tauri::AppHandle<R>,
    manager: tauri::State<'_, SettingsManager>,
    settings: Settings,
) -> Result<(), String> {
    manager.update(settings)?;
    Ok(())
}

#[tauri::command]
pub async fn set_hotkey(
    manager: tauri::State<'_, SettingsManager>,
    hotkey: String,
) -> Result<Settings, String> {
    manager.update_field(|s| s.hotkey = hotkey)
}

#[tauri::command]
pub async fn set_theme(
    manager: tauri::State<'_, SettingsManager>,
    theme: String,
) -> Result<Settings, String> {
    manager.update_field(|s| s.theme = theme)
}

#[tauri::command]
pub async fn add_excluded_app(
    manager: tauri::State<'_, SettingsManager>,
    app_id: String,
) -> Result<Settings, String> {
    manager.update_field(|s| {
        if !s.excluded_apps.contains(&app_id) {
            s.excluded_apps.push(app_id);
        }
    })
}

#[tauri::command]
pub async fn remove_excluded_app(
    manager: tauri::State<'_, SettingsManager>,
    app_id: String,
) -> Result<Settings, String> {
    manager.update_field(|s| s.excluded_apps.retain(|a| a != &app_id))
}

#[tauri::command]
pub async fn toggle_excluded_type(
    manager: tauri::State<'_, SettingsManager>,
    type_id: String,
) -> Result<Settings, String> {
    manager.update_field(|s| {
        if let Some(pos) = s.excluded_types.iter().position(|t| t == &type_id) {
            s.excluded_types.remove(pos);
        } else {
            s.excluded_types.push(type_id);
        }
    })
}
